<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <div class="widget">
                <div class="widget-body">          
                    <div class="control-group">
                        <div class="controls">
                            <label class="control-label" >Current Password</label>
                            <div class="input-prepend">
                                <span class="add-on"><i class="icon-key"></i></span>
                                <input id="userpassword" name="userpassword" type="password" placeholder="Password" />
                                <div class="error_message" id="error_userpassword"></div>
                            </div>

                            <div class="clearfix space5"></div>
                        </div>

                    </div>
                    <div class="control-group">
                        <div class="controls">
                            <label>New Password</label>
                            <div class="input-prepend">
                                <span class="add-on"><i class="icon-key"></i></span>
                                <input id="userpassword" name="reuserpassword" type="password" placeholder="Password" />
                                <div class="error_message" id="error_reuserpassword"></div>
                            </div>
                            <div class="clearfix space5"></div>
                        </div>
                    </div>
                    <div class="control-group">
                        <div class="controls">
                            <label>Re- Password</label>
                            <div class="input-prepend">
                                <span class="add-on"><i class="icon-key"></i></span>
                                <input id="userpassword" name="reuserpassword" type="password" placeholder="Password" />
                                <div class="error_message" id="error_reuserpassword"></div>
                            </div>
                            <div class="clearfix space5"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>